// <auto-generated />
using System;
using CredentialLeakageMonitoring.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CredentialLeakageMonitoring.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250505150125_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CredentialLeakageMonitoring.API.DatabaseModels.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CredentialLeakageMonitoring.API.DatabaseModels.Domain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("DomainName")
                        .IsUnique();

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("CredentialLeakageMonitoring.API.DatabaseModels.Leak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte[]>("EmailHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Domain");

                    b.HasIndex("EmailHash");

                    b.ToTable("Leaks");
                });

            modelBuilder.Entity("CustomerDomain", b =>
                {
                    b.Property<Guid>("AssociatedByCustomersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssociatedDomainsId")
                        .HasColumnType("uuid");

                    b.HasKey("AssociatedByCustomersId", "AssociatedDomainsId");

                    b.HasIndex("AssociatedDomainsId");

                    b.ToTable("CustomerDomain");
                });

            modelBuilder.Entity("CustomerLeak", b =>
                {
                    b.Property<Guid>("AssociatedCustomersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssociatedLeaksId")
                        .HasColumnType("uuid");

                    b.HasKey("AssociatedCustomersId", "AssociatedLeaksId");

                    b.HasIndex("AssociatedLeaksId");

                    b.ToTable("CustomerLeak");
                });

            modelBuilder.Entity("CustomerDomain", b =>
                {
                    b.HasOne("CredentialLeakageMonitoring.API.DatabaseModels.Customer", null)
                        .WithMany()
                        .HasForeignKey("AssociatedByCustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CredentialLeakageMonitoring.API.DatabaseModels.Domain", null)
                        .WithMany()
                        .HasForeignKey("AssociatedDomainsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerLeak", b =>
                {
                    b.HasOne("CredentialLeakageMonitoring.API.DatabaseModels.Customer", null)
                        .WithMany()
                        .HasForeignKey("AssociatedCustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CredentialLeakageMonitoring.API.DatabaseModels.Leak", null)
                        .WithMany()
                        .HasForeignKey("AssociatedLeaksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
